# ============================================== #
#          SERVER
# ============================================== #
server:
  port: 8003

# ============================================== #
#            EUREKA
# ============================================== #
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

# ============================================== #
#          LOG
# ============================================== #
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_NIVEL_PATTERN:-%5p} %m%n"