# Applicatio Configuration

server:
  port: 8005

spring:
  application:
    name: sale-microservice
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_NIVEL_PATTERN:-%5p} %m%n" 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

#* Solo etapa de desarrollo   