# ============================================== #
#          APPLICATION
# ============================================== #
spring:
  application:
    name: customer-microservice  cloud:    config:      username: root
      password: s3cr3t  config:    import: optional:configserver:http://localhost:8081