INSERT INTO MG_REGIONS (REGION_ID, REGION_NAME) VALUES (1, 'Hidalgo');
INSERT INTO MG_REGIONS (REGION_ID, REGION_NAME) VALUES (2, 'Durango');
INSERT INTO MG_REGIONS (REGION_ID, REGION_NAME) VALUES (3, 'CDMX');
INSERT INTO MG_REGIONS (REGION_ID, REGION_NAME) VALUES (4, 'Estado de México');
INSERT INTO MG_REGIONS (REGION_ID, REGION_NAME) VALUES (5, 'Queretaro');
INSERT INTO MG_REGIONS (REGION_ID, REGION_NAME) VALUES (6, 'Sinaloa');
INSERT INTO MG_REGIONS (REGION_ID, REGION_NAME) VALUES (7, 'Veracruz');
INSERT INTO MG_REGIONS (REGION_ID, REGION_NAME) VALUES (8, 'Guadalajara');

INSERT INTO MG_CUSTOMERS (CUSTOMER_ID, NUMBER_ID, CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME, CUSTOMER_EMAIL, CUSTOMER_PHOTO_URL, REGION_ID, CUSTOMER_STATE) VALUES(1,'32404580', 'Edgar', 'Martínez', 'ed.fer.mtz@gmail.com','',1,'ACTIVO');